WooCommerce v5
indodana/paylater-ecommerce-plugin-php pull request #37
Opened 2022-02-08 06:42 UTC by heggies-id

Dedicated WooCommerce v5 plugin

2022-02-08 07:18 UTC, ray1412 commented on woocommercev5/composer.json
> +  ],
I think you can add your name tho haha

2022-02-08 07:20 UTC, ray1412 commented on woocommercev5/composer.json
> +  "name": "indodana/indodana-paylater-woocommercev4",
`-woocommercev4`, is it should `v5` ?

2022-02-08 07:24 UTC, heggies-id commented on woocommercev5/composer.json
> +  "name": "indodana/indodana-paylater-woocommercev4",
whoops, on it

2022-02-09 09:43 UTC, stvyang requested changes
Please add `woocommercev5` to GitHub Action pipeline on https://github.com/indodana/paylater-ecommerce-plugin-php/tree/master/.github/workflows

2022-02-09 09:43 UTC, stvyang commented on woocommercev5/composer.json
> +  ],
Sure you can. Welcome to the club :+1:

2022-02-09 10:04 UTC, heggies-id commented on woocommercev5/composer.json
> +  ],
with pleasure 🎩

2022-02-09 10:08 UTC, stvyang commented on .github/workflows/release.yml
> +          echo "release-name=woocommerce_v4-${PACKAGE_VERSION//\./_}" >> $GITHUB_ENV
`woocommerce_v5`

2022-02-09 10:09 UTC, stvyang commented on .github/workflows/release.yml
> +          echo 'key=cache-woocommercev5-v2' >> $GITHUB_ENV
`cache-woocommercev5-v1'

The reason that i put `v2` on some package releases is due to legacy reason (I did cache using `v1` previously but some bugs). New package should use `v1`

2022-02-09 10:21 UTC, stvyang approved these changes

2022-02-09 10:28 UTC, merged